# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - baobabbot

on:
  push:
    branches:
      - integrationABCD
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build
      env:
        token: ${{ secrets.DISCORD_TOKEN }}
      run: |
        npm install
        npm run build --if-present
        npm run start
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'peacebot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2b04715df9ea481c95a355843c18d352 }}
        package: .
    - name: npm start
      env:
        token: ${{ secrets.DISCORD_TOKEN }}
      run:
        npm run start      
